# Generated by Django 4.2.5 on 2023-09-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resowner', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
