# Generated by Django 4.2.5 on 2023-09-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('red', 'RED'), ('black', 'BLACK'), ('white', 'WHITE'), ('blue', 'BLUE')], max_length=150),
        ),
    ]
