# Generated by Django 4.2.5 on 2023-09-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resadmin', '0004_alter_car_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='MALE', max_length=10),
        ),
    ]
