# Generated by Django 4.2.5 on 2023-09-27 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resadmin', '0007_alter_customer_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
