# Generated by Django 4.2.5 on 2023-09-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resadmin', '0008_remove_customer_id_alter_customer_customerid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('ownerid', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10)),
                ('age', models.CharField(max_length=100)),
                ('password', models.CharField(default='12345', max_length=150)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('contact', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'owner_table',
            },
        ),
    ]
