# Generated by Django 4.2.5 on 2023-10-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resadmin', '0009_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.CharField(default='Tata', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.CharField(default=12000, max_length=15),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(default=2012),
        ),
    ]
