# Generated by Django 4.2.5 on 2023-10-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resadmin', '0011_alter_car_manufacturer_alter_car_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ownerid',
            field=models.BigIntegerField(default=123, max_length=10),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ownerid',
            field=models.BigIntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
