# Generated by Django 4.2.5 on 2023-10-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resadmin', '0012_car_ownerid_alter_owner_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ownerid',
            field=models.BigIntegerField(max_length=10),
        ),
    ]
