# Generated by Django 4.2.5 on 2023-10-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resadmin', '0014_alter_car_ownerid_alter_owner_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ownerid',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ownerid',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
