# Generated by Django 4.2.5 on 2023-10-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resadmin', '0015_alter_car_ownerid_alter_owner_ownerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='ownerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resadmin.owner'),
        ),
    ]
